LeoShop.WebApp/Areas/Admin/Controllers/DongHoThoiTrangsController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LeoShop.Data.Models;

namespace LeoShop.WebApp.Areas.Admin.Controllers
{
    public class DongHoThoiTrangsController : Controller
    {
        private LeoShopContext db = new LeoShopContext();

        // GET: Admin/DongHoThoiTrangs
        public ActionResult Index()
        {
            if (Session["ManagerId"] == null)
                return RedirectToAction("Login", "Login");
            return View();
        }

        public PartialViewResult ContentPartial(int? size, int? page)
        {
            List<SelectListItem> listSize = new List<SelectListItem>();
            listSize.Add(new SelectListItem { Text = "4", Value = "4" });
            listSize.Add(new SelectListItem { Text = "10", Value = "10" });
            listSize.Add(new SelectListItem { Text = "15", Value = "15" });
            listSize.Add(new SelectListItem { Text = "20", Value = "20" });
            foreach (var s in listSize)
            {
                if (s.Value == size.ToString())
                    s.Selected = true;
            }
            ViewBag.Size = listSize;

            var dongHoes = (from dh in db.DongHoes.Include(d => d.ChiTietGiamGia).Include(d => d.DongHoThoiTrang).Include(d => d.ThuongHieu)
                            where dh.MaDH == dh.DongHoThoiTrang.MaDH && dh.Enable == true
                            select dh).OrderBy(dh => dh.MaDH);
            int pageNum = page ?? 1;
            int pageSize = size ?? Convert.ToInt32(listSize[0].Value); // kích thước trang mặc định
            ViewBag.CurrentSize = pageSize;
            return PartialView("ContentPartial", dongHoes.ToPagedList(pageNum, pageSize));
        }

        // GET: Admin/DongHoThoiTrangs/Details/5
        public ActionResult Details(int? id)
        {
            if (Session["ManagerId"] == null)
                return RedirectToAction("Login", "Login");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DongHo dongHo = db.DongHoes.Find(id);
            if (dongHo == null)
            {
                return HttpNotFound();
            }
            return View(dongHo);
        }

        // GET: Admin/DongHoThoiTrangs/Create
        public ActionResult Create()
        {
            if (Session["ManagerId"] == null)
                return RedirectToAction("Login", "Login");
            ViewBag.MaGG = new SelectList(db.ChiTietGiamGias, "MaGG", "MoTa");
            ViewBag.MaTH = new SelectList(db.ThuongHieux, "MaTH", "TenTH");
            ViewBag.MaDoiTuong = new SelectList(db.DoiTuongs, "MaDoiTuong", "TenDoiTuong");
            return View();
        }

        // POST: Admin/DongHoThoiTrangs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [ValidateInput(false)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaDH,TenDH,MaTH,GiaGoc,MaGG,GiaBan,SoLuong,MoTa,AnhChinhURL,Anh1URL,Anh2URL,Anh3URL,Anh4URL,DongHoThoiTrang")] DongHo dongHo)
        {
            if (ModelState.IsValid)
            {
                dongHo.AnhChinhURL = dongHo.Anh1URL = dongHo.Anh2URL = dongHo.Anh3URL = dongHo.Anh4URL = "~/Content/img/AnhDongHo/UpdatingImage.png";
                db.DongHoes.Add(dongHo);
                db.SaveChanges();
                AddImage(dongHo);
                db.Entry(dongHo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaGG = new SelectList(db.ChiTietGiamGias, "MaGG", "MoTa", dongHo.MaGG);
            ViewBag.MaTH = new SelectList(db.ThuongHieux, "MaTH", "TenTH", dongHo.MaTH);
            ViewBag.MaDoiTuong = new SelectList(db.DoiTuongs, "MaDoiTuong", "TenDoiTuong");
            return View(dongHo);
        }

        // GET: Admin/DongHoThoiTrangs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Session["ManagerId"] == null)
                return RedirectToAction("Login", "Login");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DongHo dongHo = db.DongHoes.Find(id);
            if (dongHo == null)
            {
                return HttpNotFound();
            }
            ViewBag.ChiTietGiamGias = new SelectList(db.ChiTietGiamGias, "MaGG", "MoTa", dongHo.MaGG);
            ViewBag.ThuongHieus = new SelectList(db.ThuongHieux, "MaTH", "TenTH", dongHo.MaTH);
            ViewBag.DoiTuongs = new SelectList(db.DoiTuongs, "MaDoiTuong", "TenDoiTuong");
            return View(dongHo);
        }

        // POST: Admin/DongHoThoiTrangs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [ValidateInput(false)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaDH,TenDH,MaTH,GiaGoc,MaGG,GiaBan,SoLuong,MoTa,AnhChinhURL,Anh1URL,Anh2URL,Anh3URL,Anh4URL,DongHoThoiTrang")] DongHo dongHo)
        {
            if (ModelState.IsValid)
            {
                AddImage(dongHo);
                db.Entry(dongHo).State = EntityState.Modified;
                db.Entry(dongHo.DongHoThoiTrang).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ChiTietGiamGias = new SelectList(db.ChiTietGiamGias, "MaGG", "MoTa", dongHo.MaGG);
            ViewBag.ThuongHieus = new SelectList(db.ThuongHieux, "MaTH", "TenTH", dongHo.MaTH);
            ViewBag.DoiTuongs = new SelectList(db.DoiTuongs, "MaDoiTuong", "TenDoiTuong");
            return View(dongHo);
        }

        // GET: Admin/DongHoThoiTrangs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Session["ManagerId"] == null)
                return RedirectToAction("Login", "Login");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DongHo dongHo = db.DongHoes.Find(id);
            if (dongHo == null)
            {
                return HttpNotFound();
            }
            return View(dongHo);
        }

        // POST: Admin/DongHoThoiTrangs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DongHo dongHo = db.DongHoes.Include(dh => dh.DongHoThoiTrang).Where(dh => dh.MaDH == id).FirstOrDefault();
            //string pathDirectory = Server.MapPath("~/Content/img/AnhDongHo/" + dongHo.MaDH.ToString());
            //if (Directory.Exists(pathDirectory))
            //    Directory.Delete(pathDirectory, true);
            //db.DongHoes.Remove(dongHo);
            dongHo.Enable = false;
            db.Entry(dongHo).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        private void AddImage(DongHo dongHo)
        {
            string pathDirectory = Server.MapPath("~/Content/img/AnhDongHo/" + dongHo.MaDH.ToString());
            Directory.CreateDirectory(pathDirectory);
            // Thêm hình ảnh
            for (int i = 0; i < Request.Files.Count; i++)
            {
                var image = Request.Files[i];
                if (image != null && image.ContentLength > 0)
                {
                    string extension = Path.GetExtension(image.FileName);
                    image.SaveAs(pathDirectory + "/" + i.ToString() + extension);
                    switch (i)
                    {
                        case 0: dongHo.AnhChinhURL = "~/Content/img/AnhDongHo/" + dongHo.MaDH.ToString() + "/" + i.ToString() + extension; break;
                        case 1: dongHo.Anh1URL = "~/Content/img/AnhDongHo/" + dongHo.MaDH.ToString() + "/" + i.ToString() + extension; break;
                        case 2: dongHo.Anh2URL = "~/Content/img/AnhDongHo/" + dongHo.MaDH.ToString() + "/" + i.ToString() + extension; break;
                        case 3: dongHo.Anh3URL = "~/Content/img/AnhDongHo/" + dongHo.MaDH.ToString() + "/" + i.ToString() + extension; break;
                        case 4: dongHo.Anh4URL = "~/Content/img/AnhDongHo/" + dongHo.MaDH.ToString() + "/" + i.ToString() + extension; break;
                    }
                }
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LeoShop.WebApp/Areas/Admin/Views/DongHoThoiTrangs/ContentPartial.cshtml
@model PagedList.IPagedList<LeoShop.Data.Models.DongHo>
@using PagedList.Mvc
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().MaDH)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().TenDH)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().ThuongHieu.TenTH)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().GiaGoc)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().ChiTietGiamGia.MoTa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().GiaBan)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().AnhChinhURL)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MaDH)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TenDH)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ThuongHieu.TenTH)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GiaGoc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ChiTietGiamGia.MoTa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GiaBan)
            </td>
            <td>
                <img src="@Url.Content(item.AnhChinhURL)" alt="Anh" width="50" height="50" />
            </td>
            <td>
                @Html.ActionLink("Sửa", "Edit", new { id = item.MaDH }) |
                @Html.ActionLink("Chi tiết", "Details", new { id = item.MaDH }) |
                @Html.ActionLink("Xoá", "Delete", new { id = item.MaDH })
            </td>
        </tr>
    }
</table>
<div class="row">
    <div class="col-md-6 col-lg-6 col-xs-6 col-sm-6">
        @using (Ajax.BeginForm("ContentPartial", "DongHoThoiTrangs", new AjaxOptions() { HttpMethod = "Get", UpdateTargetId = "contentPage" }))
        {
            <p>
                Kích thước trang: @Html.DropDownList("size", (List<SelectListItem>)ViewBag.Size, new { onchange = "$(this.form).submit()" })
            </p>
        }
    </div>
    <div class="col-md-6 col-lg-6 col-xs-6 col-sm-6 text-right">
        Trang: @(Model.PageNumber <= Model.PageCount ? Model.PageNumber : 0) / @Model.PageCount
    </div>
</div>
@Html.PagedListPager(Model, page => Url.Action("ContentPartial", "DongHoThoiTrangs", new { page, size = ViewBag.CurrentSize }), PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions() { HttpMethod = "Get", UpdateTargetId = "contentPage" }))

LeoShop.WebApp/Areas/Admin/Views/DongHoThoiTrangs/Create.cshtml
@model LeoShop.Data.Models.DongHo

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutPageAdmin.cshtml";
}

<h2>Thêm sản phẩm</h2>


@using (Html.BeginForm("Create", "DongHoThoiTrangs", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TenDH, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenDH, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenDH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ThuongHieu.TenTH, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.MaTH, (IEnumerable<SelectListItem>)ViewBag.MaTH, "Chọn thương hiệu", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaTH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaGoc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GiaGoc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GiaGoc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ChiTietGiamGia.MoTa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.MaGG, (IEnumerable<SelectListItem>)ViewBag.MaGG, "Chọn loại giảm giá", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaGG, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoLuong, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoLuong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoLuong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DongHoThoiTrang.LoaiMay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DongHoThoiTrang.LoaiMay, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DongHoThoiTrang.LoaiMay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DongHoThoiTrang.DuongKinhMat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DongHoThoiTrang.DuongKinhMat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DongHoThoiTrang.DuongKinhMat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DongHoThoiTrang.ChatLieuMatKinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DongHoThoiTrang.ChatLieuMatKinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DongHoThoiTrang.ChatLieuMatKinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DongHoThoiTrang.ChatLieuKhungVien, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DongHoThoiTrang.ChatLieuKhungVien, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DongHoThoiTrang.ChatLieuKhungVien, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DongHoThoiTrang.DoDayMat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DongHoThoiTrang.DoDayMat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DongHoThoiTrang.DoDayMat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DongHoThoiTrang.ChatLieuDay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DongHoThoiTrang.ChatLieuDay, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DongHoThoiTrang.ChatLieuDay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DongHoThoiTrang.DoRongDay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DongHoThoiTrang.DoRongDay, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DongHoThoiTrang.DoRongDay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DongHoThoiTrang.ThayDuocDay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                Có @Html.RadioButtonFor(model => model.DongHoThoiTrang.ThayDuocDay, true)
                Không @Html.RadioButtonFor(model => model.DongHoThoiTrang.ThayDuocDay, false)
                @Html.ValidationMessageFor(model => model.DongHoThoiTrang.ThayDuocDay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DongHoThoiTrang.TienIch, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DongHoThoiTrang.TienIch, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DongHoThoiTrang.TienIch, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DongHoThoiTrang.ChongNuoc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DongHoThoiTrang.ChongNuoc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DongHoThoiTrang.ChongNuoc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DongHoThoiTrang.NguonNangLuong, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DongHoThoiTrang.NguonNangLuong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DongHoThoiTrang.NguonNangLuong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DongHoThoiTrang.DoiTuong.TenDoiTuong, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.DongHoThoiTrang.MaDoiTuong, (IEnumerable<SelectListItem>)ViewBag.MaDoiTuong, "Chọn đối tượng sử dụng", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DongHoThoiTrang.MaDoiTuong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DongHoThoiTrang.NoiSanXuat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DongHoThoiTrang.NoiSanXuat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DongHoThoiTrang.NoiSanXuat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AnhChinhURL, htmlAttributes: new { @class = "control-label col-md-2" })
            <table class="table table-borderless va-middle">
                <tr>
                    <td width="13%">
                        <img id="mainImg" src="~/Content/img/AnhDongHo/UpdatingImage.png" alt="AnhChinh" width="100" height="100" />
                    </td>
                    <td>
                        <input type='file' id="mainInput" name="AnhChinh" width="100" />
                    </td>
                <tr>
                    <td>
                        <img id="sub1Img" src="~/Content/img/AnhDongHo/UpdatingImage.png" alt="Anh1" width="100" height="100" />
                    </td>
                    <td>
                        <input type='file' id="sub1Input" name="Anh1" width="100" />
                    </td>
                </tr>
                <tr>
                    <td>
                        <img id="sub2Img" src="~/Content/img/AnhDongHo/UpdatingImage.png" alt="Anh2" width="100" height="100" />
                    </td>
                    <td>
                        <input type='file' id="sub2Input" name="Anh2" width="100" />
                    </td>
                </tr>
                <tr>
                    <td>
                        <img id="sub3Img" src="~/Content/img/AnhDongHo/UpdatingImage.png" alt="Anh3" width="100" height="100" />
                    </td>
                    <td>
                        <input type='file' id="sub3Input" name="Anh3" width="100" />
                    </td>
                </tr>
                <tr>
                    <td>
                        <img id="sub4Img" src="~/Content/img/AnhDongHo/UpdatingImage.png" alt="Anh4" width="100" height="100" />
                    </td>
                    <td>
                        <input type='file' id="sub4Input" name="Anh4" width="100" />
                    </td>
                </tr>
            </table>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MoTa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.MoTa, new { @class = "form-control", @id = "MoTa", @row = "200" })
                <script type="text/javascript">CKEDITOR.replace('MoTa');</script>
                @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay lại", "Index")
</div>

@*Hiển thị hình ảnh xem trước khi lưu*@
<script type="text/javascript">
    function readURL(input, img) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                img.attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }

    $("#mainInput").change(function () {
        readURL(this, $("#mainImg"));
    });
    $("#sub1Input").change(function () {
        readURL(this, $("#sub1Img"));
    });
    $("#sub2Input").change(function () {
        readURL(this, $("#sub2Img"));
    });
    $("#sub3Input").change(function () {
        readURL(this, $("#sub3Img"));
    });
    $("#sub4Input").change(function () {
        readURL(this, $("#sub4Img"));
    });
</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LeoShop.WebApp/Areas/Admin/Views/DongHoThoiTrangs/Index.cshtml
@using PagedList.Mvc
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutPageAdmin.cshtml";
}

<h2>Danh sách các sản phầm Đồng hồ thời trang</h2>
<p>
    @Html.ActionLink("Thêm sản phẩm đồng hồ mới", "Create")
</p>

<div id="contentPage">@{Html.RenderAction("ContentPartial", "DongHoThoiTrangs");}</div>