LeoShop.WebApp/Areas/Admin/Controllers/AccountManagersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LeoShop.Data.Models;

namespace LeoShop.WebApp.Areas.Admin.Controllers
{
    public class AccountManagersController : Controller
    {
        private LeoShopContext db = new LeoShopContext();

        // GET: Admin/AccountManagers
        public ActionResult Index()
        {
            if (Session["ManagerId"] == null)
                return RedirectToAction("Login", "Login");
            return View(db.AccountManagers.ToList());
        }

        // GET: Admin/AccountManagers/Details/5
        public ActionResult Details(int? id)
        {
            if (Session["ManagerId"] == null)
                return RedirectToAction("Login", "Login");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AccountManager accountManager = db.AccountManagers.Find(id);
            if (accountManager == null)
            {
                return HttpNotFound();
            }
            return View(accountManager);
        }

        // GET: Admin/AccountManagers/Create
        public ActionResult Create()
        {
            if (Session["ManagerId"] == null)
                return RedirectToAction("Login", "Login");
            return View();
        }

        // POST: Admin/AccountManagers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ManagerId,Username,Pass,HoTen,NgaySinh,GioiTinh,Email,SoDT,AnhURL")] AccountManager accountManager)
        {
            if (ModelState.IsValid)
            {
                db.AccountManagers.Add(accountManager);
                db.SaveChanges();
                var avatar = Request.Files["Avatar"];
                if (avatar != null && avatar.ContentLength > 0)
                {
                    string extension = Path.GetExtension(avatar.FileName);
                    string path = Server.MapPath("~/Areas/Admin/Content/img/AvatarAccountManager/" + accountManager.ManagerId.ToString() + extension);
                    avatar.SaveAs(path);
                    accountManager.AnhURL = "~/Areas/Admin/Content/img/AvatarAccountManager/" + accountManager.ManagerId.ToString() + extension;
                }
                else
                    accountManager.AnhURL = "~/Areas/Admin/Content/img/AvatarAccountManager/DefaultAvatar.png";
                db.Entry(accountManager).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(accountManager);
        }

        // GET: Admin/AccountManagers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Session["ManagerId"] == null)
                return RedirectToAction("Login", "Login");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AccountManager accountManager = db.AccountManagers.Find(id);
            if (accountManager == null)
            {
                return HttpNotFound();
            }
            return View(accountManager);
        }

        // POST: Admin/AccountManagers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ManagerId,Username,Pass,HoTen,NgaySinh,GioiTinh,Email,SoDT,AnhURL")] AccountManager accountManager)
        {
            if (ModelState.IsValid)
            {
                var avatar = Request.Files["Avatar"];
                if (avatar != null && avatar.ContentLength > 0)
                {
                    // Xoá avatar cũ
                    string path = Server.MapPath(accountManager.AnhURL);
                    if (System.IO.File.Exists(path) && !path.Contains("DefaultAvatar.png"))
                        System.IO.File.Delete(path);
                    // Thêm avatar mới
                    string extension = Path.GetExtension(avatar.FileName);
                    path = Server.MapPath("~/Areas/Admin/Content/img/AvatarAccountManager/" + accountManager.ManagerId.ToString() + extension);
                    avatar.SaveAs(path);
                    accountManager.AnhURL = "~/Areas/Admin/Content/img/AvatarAccountManager/" + accountManager.ManagerId.ToString() + extension;
                }
                else
                {
                    // Xoá avatar cũ
                    string path = Server.MapPath(accountManager.AnhURL);
                    if (System.IO.File.Exists(path) && !path.Contains("DefaultAvatar.png"))
                        System.IO.File.Delete(path);
                    accountManager.AnhURL = "~/Areas/Admin/Content/img/AvatarAccountManager/DefaultAvatar.png";
                }
                db.Entry(accountManager).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(accountManager);
        }

        // GET: Admin/AccountManagers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Session["ManagerId"] == null)
                return RedirectToAction("Login", "Login");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AccountManager accountManager = db.AccountManagers.Find(id);
            if (accountManager == null)
            {
                return HttpNotFound();
            }
            return View(accountManager);
        }

        // POST: Admin/AccountManagers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AccountManager accountManager = db.AccountManagers.Find(id);
            string path = Server.MapPath(accountManager.AnhURL);
            db.AccountManagers.Remove(accountManager);
            db.SaveChanges();
            if (System.IO.File.Exists(path) && !path.Contains("DefaultAvatar.png"))
                System.IO.File.Delete(path);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LeoShop.WebApp/Areas/Admin/Views/AccountManagers/Create.cshtml
@model LeoShop.Data.Models.AccountManager

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutPageAdmin.cshtml";
}

<h2>Thêm tài khoản quản trị viên</h2>


@using (Html.BeginForm("Create","AccountManagers",FormMethod.Post ,new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Pass, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Pass, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pass, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HoTen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.HoTen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HoTen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgaySinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.NgaySinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgaySinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GioiTinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                Nam @Html.RadioButtonFor(m => m.GioiTinh, "Nam")
                Nữ @Html.RadioButtonFor(m => m.GioiTinh, "Nữ")
                @Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoDT, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.SoDT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoDT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AnhURL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                <img id="avatarImg" src="~/Areas/Admin/Content/img/AvatarAccountManager/DefaultAvatar.png" alt="Avatar" width="100" height="100" />
                <input type='file' id="avatarInput" name="Avatar" />
                <button type="button" id="btnClearImg">Xoá</button>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-4 col-md-10">
                <input type="submit" value="Tạo" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay lại", "Index")
</div>

@*Hiển thị hình ảnh xem trước khi lưu*@
<script type="text/javascript">
    function readURL(input, img) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                img.attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }

    $("#avatarInput").change(function () {
        readURL(this,$('#avatarImg'));
    });

    $('#btnClearImg').click(function () {
        $('#avatarInput').val(null);
        $('#avatarImg').attr('src', '/Areas/Admin/Content/img/AvatarAccountManager/DefaultAvatar.png');
    });

</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LeoShop.WebApp/Areas/Admin/Views/AccountManagers/Delete.cshtml
@model LeoShop.Data.Models.AccountManager

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutPageAdmin.cshtml";
}

<h3>Bạn có muốn xoá tài khoản này?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Username)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pass)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pass)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HoTen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoTen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgaySinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgaySinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GioiTinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GioiTinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoDT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoDT)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AnhURL)
        </dt>

        <dd>
            <img src="@Url.Content(Model.AnhURL)" alt="Avatar" width="100" height="100"/>
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xác nhận" class="btn btn-default" />
            @Html.ActionLink("Quay lại", "Index")
        </div>
    }
</div>

LeoShop.WebApp/Areas/Admin/Views/AccountManagers/Details.cshtml
@model LeoShop.Data.Models.AccountManager

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutPageAdmin.cshtml";
}

<h2>Thông tin chi tiết</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Username)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pass)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pass)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HoTen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoTen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgaySinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgaySinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GioiTinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GioiTinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoDT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoDT)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AnhURL)
        </dt>

        <dd>
            <img src="@Url.Content(Model.AnhURL)" alt="Avatar" width="100" height="100"/>
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Sửa", "Edit", new { id = Model.ManagerId }) |
    @Html.ActionLink("Quay lại", "Index")
</p>

LeoShop.WebApp/Areas/Admin/Views/AccountManagers/Edit.cshtml
@model LeoShop.Data.Models.AccountManager

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutPageAdmin.cshtml";
}

<h2>Cập nhật thông tin quản trị viên</h2>


@using (Html.BeginForm("Edit", "AccountManagers", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ManagerId)

        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control", @readonly = "true" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Pass, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Pass, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pass, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HoTen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.HoTen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HoTen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgaySinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.NgaySinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgaySinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GioiTinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                Nam @Html.RadioButtonFor(m => m.GioiTinh, "Nam")
                Nữ @Html.RadioButtonFor(m => m.GioiTinh, "Nữ")
                @Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoDT, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.SoDT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoDT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AnhURL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.HiddenFor(model => model.AnhURL)
                <img id="avatarImg" src="@Url.Content(Model.AnhURL)" alt="Avatar" width="100" height="100" />
                <input type='file' id="avatarInput" name="Avatar" />
                <button type="button" id="btnClearImg">Xoá</button>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-4 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay lại", "Index")
</div>

<script type="text/javascript">
    function readURL(input, img) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                img.attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }

    $("#avatarInput").change(function () {
        readURL(this, $('#avatarImg'));
    });

    $('#btnClearImg').click(function () {
        $('#avatarInput').val(null);
        $('#avatarImg').attr('src', '/Areas/Admin/Content/img/AvatarAccountManager/DefaultAvatar.png');
    });
</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LeoShop.WebApp/Areas/Admin/Views/AccountManagers/Index.cshtml
@model IEnumerable<LeoShop.Data.Models.AccountManager>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutPageAdmin.cshtml";
}

<h2>Danh sách tài khoản quản trị</h2>

<p>
    @Html.ActionLink("Tạo tài khoản", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Username)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HoTen)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NgaySinh)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.GioiTinh)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SoDT)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AnhURL)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Username)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HoTen)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NgaySinh)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.GioiTinh)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SoDT)
        </td>
        <td>
            <img src="@Url.Content(item.AnhURL)" alt="Avatar" width="40" height="40" />
        </td>
        <td>
            @Html.ActionLink("Sửa", "Edit", new { id=item.ManagerId }) |
            @Html.ActionLink("Chi tiết", "Details", new { id=item.ManagerId }) |
            @Html.ActionLink("Xoá", "Delete", new { id=item.ManagerId })
        </td>
    </tr>
}

</table>