LeoShop.WebApp/Areas/Admin/Controllers/DongHoThongMinhsController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LeoShop.Data.Models;

namespace LeoShop.WebApp.Areas.Admin.Controllers
{
    public class DongHoThongMinhsController : Controller
    {
        private LeoShopContext db = new LeoShopContext();

        // GET: Admin/DongHoThongMinhs
        public ActionResult Index()
        {
            if (Session["ManagerId"] == null)
                return RedirectToAction("Login", "Login");
            return View();
        }
        public PartialViewResult ContentPartial(int? size, int? page)
        {
            List<SelectListItem> listSize = new List<SelectListItem>();
            listSize.Add(new SelectListItem { Text = "4", Value = "4" });
            listSize.Add(new SelectListItem { Text = "10", Value = "10" });
            listSize.Add(new SelectListItem { Text = "15", Value = "15" });
            listSize.Add(new SelectListItem { Text = "20", Value = "20" });
            foreach (var s in listSize)
            {
                if (s.Value == size.ToString())
                    s.Selected = true;
            }
            ViewBag.Size = listSize;

            var dongHoes = (from dh in db.DongHoes.Include(d => d.ChiTietGiamGia).Include(d => d.DongHoThongMinh).Include(d => d.ThuongHieu)
                            where dh.MaDH == dh.DongHoThongMinh.MaDH && dh.Enable == true
                            select dh).OrderBy(dh => dh.MaDH);
            int pageNum = page ?? 1;
            int pageSize = size ?? Convert.ToInt32(listSize[0].Value); // kích thước trang mặc định
            ViewBag.CurrentSize = pageSize;
            return PartialView("ContentPartial", dongHoes.ToPagedList(pageNum, pageSize));
        }

        // GET: Admin/DongHoThongMinhs/Details/5
        public ActionResult Details(int? id)
        {
            if (Session["ManagerId"] == null)
                return RedirectToAction("Login", "Login");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DongHo dongHo = db.DongHoes.Find(id);
            if (dongHo == null)
            {
                return HttpNotFound();
            }
            return View(dongHo);
        }

        // GET: Admin/DongHoThongMinhs/Create
        public ActionResult Create()
        {
            if (Session["ManagerId"] == null)
                return RedirectToAction("Login", "Login");
            ViewBag.MaGG = new SelectList(db.ChiTietGiamGias, "MaGG", "MoTa");
            ViewBag.MaTH = new SelectList(db.ThuongHieux, "MaTH", "TenTH");
            return View();
        }

        // POST: Admin/DongHoThongMinhs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [ValidateInput(false)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaDH,TenDH,MaTH,GiaGoc,MaGG,GiaBan,SoLuong,MoTa,AnhChinhURL,Anh1URL,Anh2URL,Anh3URL,Anh4URL,DongHoThongMinh")] DongHo dongHo)
        {
            if (ModelState.IsValid)
            {
                dongHo.AnhChinhURL = dongHo.Anh1URL = dongHo.Anh2URL = dongHo.Anh3URL = dongHo.Anh4URL = "~/Content/img/AnhDongHo/UpdatingImage.png";
                db.DongHoes.Add(dongHo);
                db.SaveChanges();
                AddImage(dongHo);
                db.Entry(dongHo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaGG = new SelectList(db.ChiTietGiamGias, "MaGG", "MoTa", dongHo.MaGG);
            ViewBag.MaTH = new SelectList(db.ThuongHieux, "MaTH", "TenTH", dongHo.MaTH);
            return View(dongHo);
        }

        // GET: Admin/DongHoThongMinhs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Session["ManagerId"] == null)
                return RedirectToAction("Login", "Login");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DongHo dongHo = db.DongHoes.Find(id);
            if (dongHo == null)
            {
                return HttpNotFound();
            }
            ViewBag.ChiTietGiamGias = new SelectList(db.ChiTietGiamGias, "MaGG", "MoTa", dongHo.MaGG);
            ViewBag.ThuongHieus = new SelectList(db.ThuongHieux, "MaTH", "TenTH", dongHo.MaTH);
            return View(dongHo);
        }

        // POST: Admin/DongHoThongMinhs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [ValidateInput(false)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaDH,TenDH,MaTH,GiaGoc,MaGG,GiaBan,SoLuong,MoTa,AnhChinhURL,Anh1URL,Anh2URL,Anh3URL,Anh4URL,DongHoThongMinh")] DongHo dongHo)
        {
            if (ModelState.IsValid)
            {
                AddImage(dongHo);
                db.Entry(dongHo).State = EntityState.Modified;
                db.Entry(dongHo.DongHoThongMinh).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ChiTietGiamGias = new SelectList(db.ChiTietGiamGias, "MaGG", "MoTa", dongHo.MaGG);
            ViewBag.ThuongHieus = new SelectList(db.ThuongHieux, "MaTH", "TenTH", dongHo.MaTH);
            return View(dongHo);
        }

        // GET: Admin/DongHoThongMinhs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Session["ManagerId"] == null)
                return RedirectToAction("Login", "Login");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DongHo dongHo = db.DongHoes.Find(id);
            if (dongHo == null)
            {
                return HttpNotFound();
            }
            return View(dongHo);
        }

        // POST: Admin/DongHoThongMinhs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DongHo dongHo = db.DongHoes.Include(dh => dh.DongHoThongMinh).Where(dh => dh.MaDH == id).FirstOrDefault();
            //string pathDirectory = Server.MapPath("~/Content/img/AnhDongHo/" + dongHo.MaDH.ToString());
            //if (Directory.Exists(pathDirectory))
            //    Directory.Delete(pathDirectory, true);
            //db.DongHoes.Remove(dongHo);
            dongHo.Enable = false;
            db.Entry(dongHo).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        private void AddImage(DongHo dongHo)
        {
            string pathDirectory = Server.MapPath("~/Content/img/AnhDongHo/" + dongHo.MaDH.ToString());
            Directory.CreateDirectory(pathDirectory);
            // Thêm hình ảnh
            for (int i = 0; i < Request.Files.Count; i++)
            {
                var image = Request.Files[i];
                if (image != null && image.ContentLength > 0)
                {
                    string extension = Path.GetExtension(image.FileName);
                    image.SaveAs(pathDirectory + "/" + i.ToString() + extension);
                    switch (i)
                    {
                        case 0: dongHo.AnhChinhURL = "~/Content/img/AnhDongHo/" + dongHo.MaDH.ToString() + "/" + i.ToString() + extension; break;
                        case 1: dongHo.Anh1URL = "~/Content/img/AnhDongHo/" + dongHo.MaDH.ToString() + "/" + i.ToString() + extension; break;
                        case 2: dongHo.Anh2URL = "~/Content/img/AnhDongHo/" + dongHo.MaDH.ToString() + "/" + i.ToString() + extension; break;
                        case 3: dongHo.Anh3URL = "~/Content/img/AnhDongHo/" + dongHo.MaDH.ToString() + "/" + i.ToString() + extension; break;
                        case 4: dongHo.Anh4URL = "~/Content/img/AnhDongHo/" + dongHo.MaDH.ToString() + "/" + i.ToString() + extension; break;
                    }
                }
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LeoShop.WebApp/Areas/Admin/Views/DongHoThongMinhs/ContentPartial.cshtml
@model PagedList.IPagedList<LeoShop.Data.Models.DongHo>
@using PagedList.Mvc
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().MaDH)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().TenDH)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().ThuongHieu.TenTH)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().GiaGoc)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().ChiTietGiamGia.MoTa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().GiaBan)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().AnhChinhURL)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MaDH)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TenDH)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ThuongHieu.TenTH)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GiaGoc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ChiTietGiamGia.MoTa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GiaBan)
            </td>
            <td>
                <img src="@Url.Content(item.AnhChinhURL)" alt="Anh" width="50" height="50" />
            </td>
            <td>
                @Html.ActionLink("Sửa", "Edit", new { id = item.MaDH }) |
                @Html.ActionLink("Chi tiết", "Details", new { id = item.MaDH }) |
                @Html.ActionLink("Xoá", "Delete", new { id = item.MaDH })
            </td>
        </tr>
    }
</table>

<div class="row">
    <div class="col-md-6 col-lg-6 col-xs-6 col-sm-6">
        @using (Ajax.BeginForm("ContentPartial", "DongHoThongMinhs", new AjaxOptions() { HttpMethod = "Get", UpdateTargetId = "contentPage" }))
        {
            <p>
                Kích thước trang: @Html.DropDownList("size", (List<SelectListItem>)ViewBag.Size, new { onchange = "$(this.form).submit()" })
            </p>
        }
    </div>
    <div class="col-md-6 col-lg-6 col-xs-6 col-sm-6 text-right">
        Trang: @(Model.PageNumber <= Model.PageCount ? Model.PageNumber : 0) / @Model.PageCount
    </div>
</div>
@Html.PagedListPager(Model, page => Url.Action("ContentPartial", "DongHoThongMinhs", new { page, size = ViewBag.CurrentSize }), PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions() { HttpMethod = "Get", UpdateTargetId = "contentPage" }))

LeoShop.WebApp/Areas/Admin/Views/DongHoThongMinhs/Delete.cshtml
@model LeoShop.Data.Models.DongHo

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutPageAdmin.cshtml";
}

<h2>Bạn có muốn xoá sản phẩm @Model.TenDH ?</h2>

<div>
    <hr />
    <table class="table table-striped">
        <tr>
            <td colspan="2">
                <img src="@Url.Content(Model.AnhChinhURL)" alt="AnhChinh" width="100" height="100" />
                <img src="@Url.Content(Model.Anh1URL)" alt="AnhChinh" width="100" height="100" />
                <img src="@Url.Content(Model.Anh2URL)" alt="AnhChinh" width="100" height="100" />
                <img src="@Url.Content(Model.Anh3URL)" alt="AnhChinh" width="100" height="100" />
                <img src="@Url.Content(Model.Anh4URL)" alt="AnhChinh" width="100" height="100" />
            </td>
        </tr>
        <tr>
            <th width="15%">
                @Html.DisplayNameFor(model => model.MaDH):
            </th>
            <td>
                @Html.DisplayFor(model => model.MaDH)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TenDH):
            </th>
            <td>
                @Html.DisplayFor(model => model.TenDH)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ThuongHieu.TenTH):
            </th>
            <td>
                @Html.DisplayFor(model => model.ThuongHieu.TenTH)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.GiaGoc):
            </th>
            <td>
                @Html.DisplayFor(model => model.GiaGoc)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ChiTietGiamGia.MoTa):
            </th>
            <td>
                @Html.DisplayFor(model => model.ChiTietGiamGia.MoTa)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.GiaBan):
            </th>
            <td>
                @Html.DisplayFor(model => model.GiaBan)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.SoLuong):
            </th>
            <td>
                @Html.DisplayFor(model => model.SoLuong)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DongHoThongMinh.CongNgheManHinh):
            </th>
            <td>
                @Html.DisplayFor(model => model.DongHoThongMinh.CongNgheManHinh)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DongHoThongMinh.KichThuocManHinh):
            </th>
            <td>
                @Html.DisplayFor(model => model.DongHoThongMinh.KichThuocManHinh)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DongHoThongMinh.DoPhanGiai):
            </th>
            <td>
                @Html.DisplayFor(model => model.DongHoThongMinh.DoPhanGiai)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DongHoThongMinh.ChatLieuMat):
            </th>
            <td>
                @Html.DisplayFor(model => model.DongHoThongMinh.ChatLieuMat)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DongHoThongMinh.DuongKinhMat):
            </th>
            <td>
                @Html.DisplayFor(model => model.DongHoThongMinh.DuongKinhMat)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DongHoThongMinh.CPU):
            </th>
            <td>
                @Html.DisplayFor(model => model.DongHoThongMinh.CPU)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DongHoThongMinh.BoNhoTrong):
            </th>
            <td>
                @Html.DisplayFor(model => model.DongHoThongMinh.BoNhoTrong)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DongHoThongMinh.HeDieuHanh):
            </th>
            <td>
                @Html.DisplayFor(model => model.DongHoThongMinh.HeDieuHanh)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DongHoThongMinh.KetNoiHDH):
            </th>
            <td>
                @Html.DisplayFor(model => model.DongHoThongMinh.KetNoiHDH)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DongHoThongMinh.CongSac):
            </th>
            <td>
                @Html.DisplayFor(model => model.DongHoThongMinh.CongSac)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DongHoThongMinh.ThoiGianSDPin):
            </th>
            <td>
                @Html.DisplayFor(model => model.DongHoThongMinh.ThoiGianSDPin)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DongHoThongMinh.ThoiGianSac):
            </th>
            <td>
                @Html.DisplayFor(model => model.DongHoThongMinh.ThoiGianSac)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DongHoThongMinh.DungLuongPin):
            </th>
            <td>
                @Html.DisplayFor(model => model.DongHoThongMinh.DungLuongPin)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DongHoThongMinh.TheoDoiSucKhoe):
            </th>
            <td>
                @Html.DisplayFor(model => model.DongHoThongMinh.TheoDoiSucKhoe)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DongHoThongMinh.HienThiThongBao):
            </th>
            <td>
                @Html.DisplayFor(model => model.DongHoThongMinh.HienThiThongBao)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DongHoThongMinh.TienIchKhac):
            </th>
            <td>
                @Html.DisplayFor(model => model.DongHoThongMinh.TienIchKhac)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DongHoThongMinh.KetNoi):
            </th>
            <td>
                @Html.DisplayFor(model => model.DongHoThongMinh.KetNoi)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DongHoThongMinh.ChongNuoc):
            </th>
            <td>
                @Html.DisplayFor(model => model.DongHoThongMinh.ChongNuoc)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DongHoThongMinh.DoDaiDay):
            </th>
            <td>
                @Html.DisplayFor(model => model.DongHoThongMinh.DoDaiDay)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DongHoThongMinh.DoRongDay):
            </th>
            <td>
                @Html.DisplayFor(model => model.DongHoThongMinh.DoRongDay)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DongHoThongMinh.ChatLieuDay):
            </th>
            <td>
                @Html.DisplayFor(model => model.DongHoThongMinh.ChatLieuDay)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DongHoThongMinh.DayThaoRoi):
            </th>
            <td>
                @if (Model.DongHoThongMinh.DayThaoRoi == true)
                {
                    <span>Có</span>
                }
                else if (Model.DongHoThongMinh.DayThaoRoi == false)
                {
                    <span>Không</span>
                }
                else
                {
                    @Html.DisplayFor(model => model.DongHoThongMinh.DayThaoRoi)
                }
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DongHoThongMinh.NgonNgu):
            </th>
            <td>
                @Html.DisplayFor(model => model.DongHoThongMinh.NgonNgu)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DongHoThongMinh.KichThuoc):
            </th>
            <td>
                @Html.DisplayFor(model => model.DongHoThongMinh.KichThuoc)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DongHoThongMinh.TrongLuong):
            </th>
            <td>
                @Html.DisplayFor(model => model.DongHoThongMinh.TrongLuong)
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.MoTa):
            </th>
            <td>
                @Html.Raw(Model.MoTa)
            </td>
        </tr>
    </table>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xoá" class="btn btn-default" /> |
            @Html.ActionLink("Quay lại", "Index")
        </div>
    }
</div>

LeoShop.WebApp/Areas/Admin/Views/DongHoThongMinhs/Index.cshtml
@using PagedList.Mvc
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutPageAdmin.cshtml";
}

<h2>Danh sách các sản phầm Đồng hồ thông minh</h2>
<p>
    @Html.ActionLink("Thêm sản phẩm đồng hồ mới", "Create")
</p>

<div id="contentPage">@{Html.RenderAction("ContentPartial", "DongHoThongMinhs");}</div>